#!/usr/bin/env python3
"""Interactive API key setup script for SciTrans.

This script helps you configure API keys for various translation backends.
"""

from pathlib import Path


def get_env_file_path() -> Path:
    """Get path to .env file in project root."""
    # Assume script is in scripts/, so project root is parent
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    return project_root / ".env"


def load_env_file(env_path: Path) -> dict[str, str]:
    """Load existing .env file."""
    env_vars = {}
    if env_path.exists():
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, value = line.split("=", 1)
                    env_vars[key.strip()] = value.strip()
    return env_vars


def save_env_file(env_path: Path, env_vars: dict[str, str]) -> None:
    """Save .env file."""
    with open(env_path, "w") as f:
        f.write("# SciTrans API Keys\n")
        f.write("# Generated by scripts/setup_api_keys.py\n\n")
        for key, value in sorted(env_vars.items()):
            f.write(f"{key}={value}\n")


def prompt_api_key(
    backend_name: str, key_name: str, description: str, current_value: str | None
) -> str | None:
    """Prompt user for an API key."""
    print(f"\n{'=' * 60}")
    print(f"{backend_name}")
    print(f"{'=' * 60}")
    print(f"{description}")

    if current_value:
        print(
            f"\nCurrently set: {current_value[:10]}..."
            if len(current_value) > 10
            else f"\nCurrently set: {current_value}"
        )
        prompt = "Enter new value (or press Enter to keep current): "
    else:
        prompt = "Enter API key (or press Enter to skip): "

    value = input(prompt).strip()

    if not value and current_value:
        return current_value

    return value if value else None


def main():
    print("SciTrans API Key Setup")
    print("=" * 60)
    print("\nThis script will help you configure API keys for translation backends.")
    print("You can skip any backend by pressing Enter.\n")

    env_path = get_env_file_path()
    env_vars = load_env_file(env_path)

    # Anthropic (Claude)
    anthropic_key = prompt_api_key(
        "Anthropic (Claude)",
        "ANTHROPIC_API_KEY",
        "Get your key at: https://console.anthropic.com/",
        env_vars.get("ANTHROPIC_API_KEY"),
    )
    if anthropic_key:
        env_vars["ANTHROPIC_API_KEY"] = anthropic_key

    # OpenAI / Cascade
    openai_key = prompt_api_key(
        "OpenAI / Cascade",
        "OPENAI_API_KEY",
        "Get your key at: https://platform.openai.com/api-keys\n"
        "Or use Cascade/TogetherAI/etc. with OPENAI_BASE_URL",
        env_vars.get("OPENAI_API_KEY"),
    )
    if openai_key:
        env_vars["OPENAI_API_KEY"] = openai_key

        # Optional: custom base URL
        base_url = input("\nCustom API base URL (optional, press Enter to skip): ").strip()
        if base_url:
            env_vars["OPENAI_BASE_URL"] = base_url

    # HuggingFace
    hf_key = prompt_api_key(
        "HuggingFace",
        "HUGGINGFACE_API_KEY",
        "Get your key at: https://huggingface.co/settings/tokens\n"
        "(Optional for free tier, required for faster endpoints)",
        env_vars.get("HUGGINGFACE_API_KEY"),
    )
    if hf_key:
        env_vars["HUGGINGFACE_API_KEY"] = hf_key

    # Ollama (local, no API key)
    print(f"\n{'=' * 60}")
    print("Ollama (Local)")
    print(f"{'=' * 60}")
    print("Ollama runs locally and doesn't require an API key.")
    print("Install from: https://ollama.ai/")
    ollama_host = input("Ollama host (default: http://localhost:11434): ").strip()
    if ollama_host:
        env_vars["OLLAMA_HOST"] = ollama_host

    # Google Translate (free, no API key)
    print(f"\n{'=' * 60}")
    print("Google Translate (Free)")
    print(f"{'=' * 60}")
    print("The free Google Translate backend doesn't require an API key.")
    print("It's rate-limited and may be unreliable for production use.")

    # Save .env file
    print(f"\n{'=' * 60}")
    print("Summary")
    print(f"{'=' * 60}")
    print(f"\nAPI keys will be saved to: {env_path}")
    print(f"Keys configured: {len([k for k in env_vars.keys() if k.endswith('_KEY')])}")

    save_choice = input("\nSave configuration? (y/n): ").strip().lower()

    if save_choice == "y":
        save_env_file(env_path, env_vars)
        print(f"\n✓ Configuration saved to {env_path}")
        print("\nTo use these keys, either:")
        print("  1. Load the .env file: export $(cat .env | xargs)")
        print("  2. Or add this to your shell profile:")
        print(f"     source {env_path}")
    else:
        print("\nConfiguration not saved.")

    print("\nDone! You can now use SciTrans with your configured backends.")


if __name__ == "__main__":
    main()
